name: CI workflow

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  test:
    uses: darkgl0w/workflows/.github/workflows/plugins-ci.yml@exp-alt
    with:
      lint: true
      test-script: 'test:ci'
      run-on-node-current-branch: true