name: CI workflow

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  linter:
    uses: darkgl0w/workflows/.github/workflows/linter-ci.yml@linter-ci

  test:
    needs: linter
    uses: darkgl0w/workflows/.github/workflows/plugins-ci.yml@linter-ci
